---
title: "HW4"
author: "Valeria"
date: "2024-05-15"
output: html_document
---

```{r}
library(vegan)
library(dplyr)
library(readxl)
library(zoo)
library("class")
```

Data
```{r}
fauna <- read_excel('Grazing_Magierowski_et_al_2015.xls', sheet = 'fauna')
env <- read_excel('Grazing_Magierowski_et_al_2015.xls', sheet = 'env')
fauna <- fauna[, -1]
env <- env[,-1]
```

```{r}
sum(is.na(fauna))
sum(is.na(env))
```


```{r}
boxplot(env[,-ncol(env)])
```
need to be log and norm

```{r}
env <- as.data.frame(scale(log(env[,-ncol(env)]+1), scale = FALSE))
boxplot(env)
```

CCA
```{r}
df <- read_excel('Grazing_Magierowski_et_al_2015.xls', sheet = 'env')
env_cca <- as.data.frame(na.aggregate(env, FUN = mean))
env_cca$GrazingRank <- df$GrazingRank
sum(is.na(env_cca))
```

```{r}
graze_cca <- cca(fauna ~ ., data = env_cca)
summary(graze_cca)
```
```{r}
vif.cca(graze_cca)
```
```{r}
plot(graze_cca, scaling ="sites", main = "scaling 1")
```
```{r}
plot(graze_cca, scaling ="species")
```
```{r}
anova(graze_cca, by="term")
anova(graze_cca, by = "mar")
```
CCA model shows statistical significance, highlighting the crucial role of external factors in population formation. The key external factors driving changes in flora and fauna composition are temperature, and average turbidity.